//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDelershipWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarComments
    {
        public int CarComment_Id { get; set; }
        public int Car_Id { get; set; }
        public int Author_Id { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public string ApprovedBy { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Users Users { get; set; }
    }
}
