//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDelershipWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedbacks
    {
        public int Feedback_Id { get; set; }
        public int User_Id { get; set; }
        public string UserName { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<System.DateTime> ProcessedAt { get; set; }
        public string ProcessedBy { get; set; }
        public string AdminComment { get; set; }
        public bool IsClosed { get; set; }
        public bool IsClosedByUser { get; set; }
        public string IsReadByUser { get; set; }
    }
}
