//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDelershipWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Models
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Models()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int Model_Id { get; set; }
        public int Manufacturer_Id { get; set; }
        public string Name { get; set; }
        public int BodyType_Id { get; set; }
        public int EngineType_Id { get; set; }
        public int Power { get; set; }
        public int Transmission_Id { get; set; }
    
        public virtual BodyTypes BodyTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
        public virtual EngineTypes EngineTypes { get; set; }
        public virtual Manufacturers Manufacturers { get; set; }
        public virtual Transmissions Transmissions { get; set; }
    }
}
