//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDelershipWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItems
    {
        public int OrderItem_Id { get; set; }
        public int Order_Id { get; set; }
        public int Car_Id { get; set; }
        public int Quantity { get; set; }
        public decimal PriceAtPurchase { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
