//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDelershipWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceHistory
    {
        public int PriceHistory_Id { get; set; }
        public int Car_Id { get; set; }
        public decimal OldPrice { get; set; }
        public decimal NewPrice { get; set; }
        public decimal OldDiscountPrice { get; set; }
        public decimal NewDiscountPrice { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public string ChangedBy { get; set; }
        public string ChangeReason { get; set; }
    
        public virtual Cars Cars { get; set; }
    }
}
