//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDelershipWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplyItems
    {
        public int SupplyItem_Id { get; set; }
        public int Supply_Id { get; set; }
        public int Car_Id { get; set; }
        public int Quantity { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Supplies Supplies { get; set; }
    }
}
