//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDelershipWPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplies()
        {
            this.SupplyItems = new HashSet<SupplyItems>();
        }
    
        public int Supply_Id { get; set; }
        public int Supplier_Id { get; set; }
        public int Status_Id { get; set; }
        public Nullable<System.DateTime> CompletedAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual StatusSupplies StatusSupplies { get; set; }
        public virtual Suppliers Suppliers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplyItems> SupplyItems { get; set; }
    }
}
